  CREATE TABLE "ORACLE"."USERS" 
   (	"ID" NUMBER(5,0) NOT NULL ENABLE, 
	"COMPANY_ID" NUMBER(2,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CREATED_AT" DATE NOT NULL ENABLE, 
	 CONSTRAINT "FK_USERS_COMPANY_ID" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "ORACLE"."COMPANIES" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TABL" 
  CREATE UNIQUE INDEX "ORACLE"."PK_USERS" ON "ORACLE"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDX" 
ALTER TABLE "ORACLE"."USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("ID")
  USING INDEX "ORACLE"."PK_USERS"  ENABLE;
